version: 2
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.0
    parallelism: 1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install
      - run: sudo apt-get update --allow-releaseinfo-change
      - run:
          name: Run tests
          command: rake test
workflows:
  version: 2
  test:
    jobs:
      - test
